export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SETTINGS = "GET_SETTINGS";
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const PLAN_LOADING = "PLAN_LOADING";
export const GET_FOOD_PLANS = "GET_FOOD_PLANS";
export const GET_ACTIVITY_PLANS = "GET_ACTIVITY_PLANS";
export const GET_PLAN = "GET_PLAN";
